Rdp = {
    {nordp = 1, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 1, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 1, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 2, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 2, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 2, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 3, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 3, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 3, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 4, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 4, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 4, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 5, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 5, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 5, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 6, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 6, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 6, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 7, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 7, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 7, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 8, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 8, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 8, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 9, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 9, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 9, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 10, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 10, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 10, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 11, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 11, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 11, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 12, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 12, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 12, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 13, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 13, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 13, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 14, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 14, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 14, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 15, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 15, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 15, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 16, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 16, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 16, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 17, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 17, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 17, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 18, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 18, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 18, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 19, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 19, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 19, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 20, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 20, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 20, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 21, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 21, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 21, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 22, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 22, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 22, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 23, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 23, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 23, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 24, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 24, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 24, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 25, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 25, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 25, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 26, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 26, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 26, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 27, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 27, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 27, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 28, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 28, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 28, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 29, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 29, botname = "Bot1", Status = "Nonaktif"},
    {nordp = 29, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 30, botname = "Bot2", Status = "Nonaktif"},
    {nordp = 30, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 30, botname = "Bot3", Status = "Nonaktif"},
    {nordp = 31, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 31, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 31, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 32, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 32, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 32, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 33, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 33, botname = "Bot4", Status = "Nonaktif"},
    {nordp = 33, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 34, botname = "Bot5", Status = "Nonaktif"},
    {nordp = 34, botname = "Bot6", Status = "Nonaktif"},
    {nordp = 34, botname = "Bot6", Status = "Nonaktif"},
}

ShowIP = false
ip_add = {
}

hookURL = "https://discord.com/api/webhooks/1034955599588364339/3WkcKBCWS48JvMWa7Ifb2S0KC4U5N_Fx7iuHJcbEC2sDurt4ahzMEQ9WTEZG16bxNYn7"

Teks_Deskripsi = "List Nick Para Babu"
Teks_Footer = "Golek Duit Kanggo Masa Depan"

Emote_Offline = "<:offline:982957367392088124>"
Emote_Online = "<:online:982957403756716052>"

menit = 3 --TIAP BERAPA MENIT BOTNYA NGIRIM WEBHOOK